### ISSUE TITLE
power.R S3 output

### ISSUE THREAD

**Issue by fredjaya** [AngusMcLure/PoolPoweR#36]
Hey @AngusMcLure, I have just [pushed a draft](https://github.com/AngusMcLure/PoolPoweR/commit/2bce2e7bec21dcf64d1525d56feaf50c4526831b) of what an output class for `power_pool()` could look like, based on the pretty print for `stats::power.prop.test`.  

Need to fix the way pretty print is triggered (e.g. instead of str()), but this is the current command to get the output below
```r
power_pool(cluster_number = 11, pool_number = 2, pool_size = 10, prevalence_null = 0.01, prevalence_alt = 0.02)
```

```
      pool_size = 10
    pool_number = 2
 cluster_number = 50
      prev_null = 0.01
       prev_alt = 0.02
      sig_level = 0.05
      --> power = 0.7617911
    alternative = greater
```

Could you indicate/suggest:
- [ ] The variables to be output across all functions (e.g. `sample_size_pool` has total pools)
- [ ] Anything regarding presentation of names/formatting
- [ ] A better name for the output class - it's currently "power_size_results"

**Comment by AngusMcLure** [comment]
I've had a look and think I fixed up the roxygen issue that was preventing the print method from registering properly. I also fixed the issues with pool_strat method documentation while I was at it.

Also responses to your questions:
* The outputs _will_ have to be somewhat different across functions and possible inputs. For the _random functions you will have catch distribution and pool strategy inputs instead of pool number and size. I think it is worth including these as outputs but making it clear by the name that these are per cluster to distinguish them from the totals
* You definitely also want the correlation, and probably also the test sensitivity and specificity (though perhaps only if they are not equal to 1?)
* You probably want to consistently output the total number of units, pools, and clusters (for the _random functions this will be the expected number of units and pools).
* In terms of output format, I wonder if you could have three groups of outputs separated by horizontal lines:
    * Sample design: pool size/pool_strat, pool number/ catch_distribution, clusters, total (expected) units, total (expected) pools
    * Prevalence assumptions: prev_alt, prev_null, correlation
    * Statistical test: sig_level, power, alternative
    * Test characteristics: Sensitivity, Specificity (perhaps omit if a perfect test)

This is potentially quite a lot of results to display, but I think it makes sense to display these.

One bridge to cross is how to display the pool_strat function in a pretty way. I've created a as.character method for it which just return the call as a character, but this might not be an ideal way to represent it.

Happy to discuss more if there are issues/questions

**Comment by fredjaya** [comment]
Example print output as discussed:
```
DIAGNOSTIC TEST
sensitivity = 
specificity = 

   PREVALENCE
   prev_alt = 
  prev_null =
correlation = 

STATISTICAL TEST
  sig_level = 
      power =
alternative = 

SAMPLE DESIGN
  pool size = 
   pool num = 
   clusters = 
total units =
total pools =

Placeholder sentence with the inferred value (e.g. power) and some prose 
```

pool strat and pool catch when using `*_random()`

**Comment by AngusMcLure** [comment]
Just noting that we want to make sure that the output/input names match the output/input names in the pretty print layout. Specifically I am thinking about the _ that are present/absent in some of the above names?

**Comment by AngusMcLure** [comment]
Looks great.

Two suggestions:

* change the power print output there to be 3 decimal places if that's not too hard. Note that the actual result shouldn't be rounded, just the way you print to screen. E.g. power_pool(...)$power should give you a number to lots of decimal places but the default print method for the output of power_pool(...) should only have 3dp?
* The subject of the summary sentence should probably be 'survey design'. E.g. 'A survey design using an imperfect test on pooled samples with the above parameters has a statistical power of X'


My guess is that we'll have to iterate on what goes into the summary sentences as we look at the different functions!

**Comment by fredjaya** [comment]
Agree with the rounding when printing! Would still like to keep "imperfect _diagnostic_ test" for clarity
